### ISSUE TITLE
Error when running demo in Chrome OSX

### ISSUE THREAD

**Issue by SmallRoomLabs** [Jack000/SVGnest#1]
Clicking on the Demo button using Chrome version 49.0.2623.0 canary (64-bit) under OSX only gives an error in the bottom of the app window. 

`TypeError: Cannot read property 'length' of undefined`

**Comment by Jack000** [comment]
this appears to be related to the deprecation of the SVGPathSeg APIs:
https://groups.google.com/a/chromium.org/forum/?fromgroups#!topic/blink-dev/EDC3cBg9mCU

unfortunately the "new and improved" APIs don't appear to have been implemented yet, so I'll have to look at the polyfill for it to work with Canary.

**Comment by Jack000** [comment]
added polyfill and updated svgnest.com

chrome 47+ should be ok now

**Comment by SmallRoomLabs** [comment]
Awesome... it works just fine now.  
This for sure beats hand-placing a lot of parts before cutting!
:+1:
