### ISSUE TITLE
Not allowing parts to be rotated at all

### ISSUE THREAD

**Issue by karpour** [Jack000/SVGnest#10]
I think this tool would be great for figuring out efficient cutting for fabric as well, however with some fabric it is essential that none of the parts get rotated at all due to the fabric structure.
Setting "Part Rotations" to 0 or 1 still caused the parts to be rotated, I would suggest an option to not rotate any parts.

**Comment by Jack000** [comment]
setting rotations to 1 should ensure all parts maintain their orientation.

I think you may have clicked the x icon instead of "save". That cancels the config change instead of saving it, but I guess it's a bit ambiguous.

**Comment by karpour** [comment]
Oh, I just realized what happened! The Save button was covered by the "Click on outline to use as the bin" message, so I assumed settings were saved automatically.

Thanks for the quick reply and the great work!
