### ISSUE TITLE
Make your logo on website return home

### ISSUE THREAD

**Issue by cojarbi** [Jack000/SVGnest#16]
Currently it doesn't do anything. To start all over had to refresh the site. At least in chrome

**Comment by thopman** [comment]
why the hell do i get these emails?



Thomas Hopman - TomaTek - Paradiso - SureShot Studio
+31 (0)6 17115051

2016-02-12 4:52 GMT+01:00 Ariel Yahni <notifications@github.com>:

**Comment by servant74** [comment]
You are subscribed to these notifications.  You can change it by logging
into github and changing your settings.

On Fri, Feb 12, 2016 at 8:38 AM, Thomas Hopman <notifications@github.com>
wrote:

> why the hell do i get these emails?
>
>
>
> Thomas Hopman - TomaTek - Paradiso - SureShot Studio
> +31 (0)6 17115051
>
> 2016-02-12 4:52 GMT+01:00 Ariel Yahni <notifications@github.com>:
>
> > Currently it doesn't do anything. To start all over had to refresh the
> > site. At least in chrome
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Jack000/SVGnest/issues/16>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jack000/SVGnest/issues/16#issuecomment-183355068>.
>



-- 
><> ... Jack

The Four Boxes of Liberty - "There are four boxes to be used in the defense
of liberty: soap, ballot, jury and ammo. Please use in that order."
"Whatever you do, work at it with all your heart"... Colossians 3:23
"Anyone who has never made a mistake, has never tried anything new." -
Albert Einstein
"You don't manage people; you manage things. You lead people." - Admiral
Grace Hopper, USN
"The most dangerous phrase in the language is "We’ve always done it this
way"-- Admiral Grace Hopper, USN
"Tell me and I forget. Teach me and I remember. Involve me and I learn." -
Ben Franklin

**Comment by Jack000** [comment]
added the link
