### ISSUE TITLE
fill holes

### ISSUE THREAD

**Issue by losbellos** [Jack000/SVGnest#22]
Hello,

Is that possible that the code fills the holes, for example an "O" characters inside?
I have some ideas for acceleration if you like it. For example using angles that pre-caclulated on polygons etc, to obtain the likely possible best rotation to fit to the cutout etc.

**Comment by losbellos** [comment]
Oh I see you have this in the to do list!

**Comment by losbellos** [comment]
I thought of something, what if you open or brake all "holy" shapes then the algorithm can work in it, you only need to make sure that the hole is small that no other shapes can fit there, but the usual algorithm still works on it. Only flag it and replace it then with the original closed "holy" shapes.

It is possible to make such opening by math.

**Comment by Jack000** [comment]
just added this feature as an optional toggle in the settings. Let me know if you have any issues with it.
