### ISSUE TITLE
type error Cannot read property x of undefined

### ISSUE THREAD

**Issue by PlastecProfiles** [Jack000/SVGnest#24]
What do I do about this?

**Comment by Jack000** [comment]
which browser/os is this?

**Comment by PlastecProfiles** [comment]
Chrome on windows 10

**Comment by Jack000** [comment]
hm.. which version of chrome? does it error on the demo?

**Comment by gaetancollaud** [comment]
Same issue:
```
TypeError: Cannot read property 'x' of undefined
    at SvgParser.polygonify (http://svgnest.com/svgparser.js:671:42)
    at SvgNest.getParts (http://svgnest.com/svgnest.js:557:26)
    at SvgNest.parsesvg (http://svgnest.com/svgnest.js:54:16)
    at FileReader.reader.onload (http://svgnest.com/:300:33)
```

The problem seem's to be here: https://github.com/Jack000/SVGnest/blob/master/svgparser.js#L670-L674 You pop an item of the array but didn't check if the array is empty.

I will try to fix this. I will make a PR if I it works

**Comment by gaetancollaud** [comment]
That was the issue. Find the PR #29
