### ISSUE TITLE
Nesting messed up when input with the output of the demo

### ISSUE THREAD

**Issue by md1053** [Jack000/SVGnest#26]
I've tried to use the output of the demo as an input, because was having difficulty in using my test profiles. I noticed that when demo has been run with 0 spacing, the subsequent nesting performed on it gives some white filled shapes placed outside the bin, and many shapes wildly overlap.
If the demo is run with 0.5 spacing, using this output gives a fine result.
![cattura](https://cloud.githubusercontent.com/assets/21359212/18125795/5d0b690e-6f78-11e6-8cb1-4b941eed300a.JPG)

**Comment by Jack000** [comment]
do you mean you downloaded the nested svg, then uploaded that and nested it again? That will result in many pieces that touch eachother, which makes it ambiguous which outlines are shapes and which are holes.

could you send me the test profile you were having problems with?
