### ISSUE TITLE
"Performs similarly to commercial software"... which one?

### ISSUE THREAD

**Issue by Pomax** [Jack000/SVGnest#3]
There's probably more than one application that can do packing, which one are you benchmarking against? (because this is a bit like saying "our toothpaste is 30% better than the next leadin brand"... there's no true information there =D)

**Comment by Jack000** [comment]
I just didn't want to call them out specifically. But it's the one with the pay-per-use model : ]

**Comment by Pomax** [comment]
that's kind of the problem: if you don't call them out by name specifically, the comparison's mostly meaningless. There's quite a few commercially available products that can do packing (we can even count stuff like Mathematica), so even that hint is not really enough to know which one you're talking about =)

**Comment by Jack000** [comment]
I think mynesting is the only one with a pay-per-use model. There's also nestfab which uses the same engine. In the demo case most nesting programs will give you very similar results because the underlying algorithms tend to be very similar.

**Comment by Pomax** [comment]
I see. There's also usually Matlab/python/etc implementations that come with papers on packing algorithms, it would be interesting to see how this performs in comparison (Although obviously a chore to benchmark =)
