### ISSUE TITLE
Download SVG Error!

### ISSUE THREAD

**Issue by lancer99** [Jack000/SVGnest#31]
Not able to download the final nested SVG. I tried to download svg after the demo nesting is finished. Got the below error on opening it.

This page contains the following errors:

error on line 1 at column 617: Attribute version redefined
Below is a rendering of the page up to the first error.

Chrome V54

**Comment by Jack000** [comment]
hey lancer

I haven't been able to reproduce this on Chrome 54, what's the full error message?

**Comment by lancer99** [comment]
Hi Jack

Below is the error message. 

This page contains the following errors:

error on line 1 at column 617: Attribute version redefined
Below is a rendering of the page up to the first error.

 When i try to open the file in inkscape or any other svg viewer.

![ss](https://cloud.githubusercontent.com/assets/23209701/20029189/f51294a8-a36b-11e6-8491-effcdf200a91.png)

**Comment by Jack000** [comment]
oh I see, the error is when you load the svg output

I removed the inkscape specific tags from the demo svg, should work now.
