### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by baojinsong** [Jack000/SVGnest#4]
When I uploaded the svg file:

<svg viewBox = "0 0 1100 400" version = "1.1">
     <path id = "s3" d = "M 60 0 L 120 0 L 180 60 L 180 120 L 120 180 L 60 180 L 0 120 L 0 60" fill = "green" stroke = "black" stroke-width = "3"/>
 </svg>

An error is occurred.
TypeError: unable to get property "getAttribute" of undefined or null reference.

Has the file any error? 

Will you give any samples in the demo project?

**Comment by Jack000** [comment]
does the demo have the same error? What browser/version are you using?

**Comment by baojinsong** [comment]
Oh, I have found it is the browser's problem. MS Edge can't run the demo.

**Comment by Jack000** [comment]
ah, have't tested in edge yet. I'll have to look into that
