### ISSUE TITLE
Can run demo at local？

### ISSUE THREAD

**Issue by baojinsong** [Jack000/SVGnest#5]
![run_svgnest com](https://cloud.githubusercontent.com/assets/10363943/12390258/52af0a80-be19-11e5-8f5e-5861a15174c0.JPG)

When run demo at svgnest.com, All are fine.

![run_local](https://cloud.githubusercontent.com/assets/10363943/12390260/5493d394-be19-11e5-88d8-47ae9284d1b8.JPG)
Download src and extract it into a local directory and run the demo again. 
Progress bar is disappeared. nothing was happened.

**Comment by Jack000** [comment]
yes this is a limitation of webworkers. It needs to be hosted somewhere to run multiple threads.

SVGnest uses parallel processing to speed up the algorithm (4-8 threads depending on system), which doesn't work when opening the file in explorer/finder.
