### ISSUE TITLE
Packing shapes within defined areas

### ISSUE THREAD

**Issue by dylib** [Jack000/SVGnest#63]
Is it possible to alter a shape to fit within a particular area? I'm not sure what the terminology is called for this process, or if there's already an algorithm that handles things such as this. Basically I have a defined shape that I'm looking to fill with others from an adjacency matrix. Ideally it the algorithm would be able to define which shapes can be altered to fit (while keeping approximately the same overall area size). Here's an example:

![pack_shapes_color](https://user-images.githubusercontent.com/17288131/38480011-c7619f72-3b77-11e8-91a2-7e9ab56c4e51.gif)

Any thoughts on how to do this or advice is welcomed, thanks.

**Comment by Jack000** [comment]
so if I'm getting this right the final shape should be partitioned into r/b/y without any blank spaces?  I guess you could do a normal bin packing using a fitness function that doesn't punish out-of-bounds shapes if they can be altered, then clip off the outside parts.

is there a larger problem you're trying to solve? I'm not quite seeing what this could be for.

**Comment by dylib** [comment]
Thank you for your response. Yes, what you describe is more or less what I'm trying to figure out how to do. I suppose there could be some blank space between the shapes as long as it followed the same paths. 

Basically I haven't been able to figure out what would need to be done so that shape 3 for example is sliced up and the total area that it encompasses is refitted to it somehow so that it can be placed within it's region. You could think of it almost like a decision tree map, or random forest map but using shapes instead of rectangles if that makes any sense. 

I realize your project might not be the right thing to use in this circumstance, and I thought about possibly asking this question on stackoverflow perhaps, although you obviously have extensive knowledge in this area so I thought it wouldn't hurt to ask.

**Comment by Jack000** [comment]
I think the keyword you're looking for is https://en.wikipedia.org/wiki/Polygon_partition

I haven't looked into partitioning algorithms that much, but I think you could just do a Delaunay triangulation of your outer shape, choose a random triangle and fill in connected triangles until you have the area of the country you want, the repeat the process.

**Comment by dylib** [comment]
Yep, that's pretty close to what I'm looking to do — [here's another example](https://bl.ocks.org/veltman/c582a31d347e04dd75d5331b0074558e
). So would you say that your project really wouldn't be the thing to use for that type of thing?

**Comment by Jack000** [comment]
yeah bin packing doesn't seem to fit what you're looking for, it would be pretty hard to hack my code to do what you want imo. That example is pretty much exactly what I'd do for this type of problem.

**Comment by dylib** [comment]
Alrighty, well appreciate the advice and time you've offered — thank you!

Impressive work on your project nonetheless, cheers :)

**Comment by Jack000** [comment]
thanks : ]
