### ISSUE TITLE
Nesting skips available space

### ISSUE THREAD

**Issue by finnyexeeson** [Jack000/SVGnest#73]
Hi Jack, I was trying to nest a few 10X10 cubes into a 20X10 bin and the algorithm seems to skip the remaining space in the bin

Input:
![image](https://user-images.githubusercontent.com/18449719/44805860-30547000-ab7a-11e8-8d30-bfdb7a0d5a14.png)
Output:
![image](https://user-images.githubusercontent.com/18449719/44805898-43ffd680-ab7a-11e8-9f27-319825017ab3.png)

Default config setting.

input svg:
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 170 30" preserveAspectRatio="xMinYMin meet"><polygon id="1" fill="none" stroke="blue" stroke-width="10" points="0,0  0,10  10,10  10,0  0,0 "></polygon><polygon id="2" fill="none" stroke="blue" stroke-width="10" points="10,0  10,10  20,10  20,0  10,0 "></polygon><polygon id="3" fill="none" stroke="blue" stroke-width="10" points="20,0  20,10  30,10  30,0  20,0 "></polygon><polygon id="4" fill="none" stroke="blue" stroke-width="10" points="30,0  30,10  40,10  40,0  30,0 "></polygon><polygon id="5" fill="none" stroke="blue" stroke-width="10" points="40,0  40,10  50,10  50,0  40,0 "></polygon><polygon id="6" fill="none" stroke="blue" stroke-width="10" points="50,0  50,10  60,10  60,0  50,0 "></polygon><polygon id="7" fill="none" stroke="blue" stroke-width="10" points="60,0  60,10  70,10  70,0  60,0 "></polygon><polygon id="8" fill="none" stroke="blue" stroke-width="10" points="70,0  70,10  80,10  80,0  70,0 "></polygon><polygon id="9" fill="none" stroke="blue" stroke-width="10" points="80,0  80,10  90,10  90,0  80,0 "></polygon><polygon id="10" fill="none" stroke="blue" stroke-width="10" points="90,0  90,10  100,10  100,0  90,0 "></polygon><polygon id="11" fill="none" stroke="blue" stroke-width="10" points="100,0  100,10  110,10  110,0  100,0 "></polygon><polygon id="12" fill="none" stroke="blue" stroke-width="10" points="110,0  110,10  120,10  120,0  110,0 "></polygon><polygon id="13" fill="none" stroke="blue" stroke-width="10" points="120,0  120,10  130,10  130,0  120,0 "></polygon><polygon id="14" fill="none" stroke="blue" stroke-width="10" points="130,0  130,10  140,10  140,0  130,0 "></polygon><polygon id="15" fill="none" stroke="blue" stroke-width="10" points="140,0  140,10  150,10  150,0  140,0 "></polygon><polygon id="16" fill="none" stroke="blue" stroke-width="10" points="150,0  150,10  160,10  160,0  150,0 "></polygon><polygon id="17" fill="none" stroke="blue" stroke-width="10" points="160,0  160,10  170,10  170,0  160,0 "></polygon><polygon id="" fill="none" stroke="blue" stroke-width="10" points="160,0 "></polygon><rect id="binRect" x="0" y="10" width="10" height="20"></rect></svg>

Br

**Comment by Jack000** [comment]
if your bin is exactly 10x20 there is some uncertainty in whether the part will fit. Maybe try making the bin 10.01x20.01

**Comment by finnyexeeson** [comment]
i tried with bigger 10.01X, 20.01, 10.05X20.05 and 10.05X30.05 with out any success

**Comment by Jack000** [comment]
hm.. could you attach the svg?

**Comment by finnyexeeson** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 170 30" preserveAspectRatio="xMinYMin meet"><polygon id="1" fill="none" stroke="blue" stroke-width="10" points="0,0  0,10  10,10  10,0  0,0 "></polygon><polygon id="2" fill="none" stroke="blue" stroke-width="10" points="10,0  10,10  20,10  20,0  10,0 "></polygon><polygon id="3" fill="none" stroke="blue" stroke-width="10" points="20,0  20,10  30,10  30,0  20,0 "></polygon><polygon id="4" fill="none" stroke="blue" stroke-width="10" points="30,0  30,10  40,10  40,0  30,0 "></polygon><polygon id="5" fill="none" stroke="blue" stroke-width="10" points="40,0  40,10  50,10  50,0  40,0 "></polygon><polygon id="6" fill="none" stroke="blue" stroke-width="10" points="50,0  50,10  60,10  60,0  50,0 "></polygon><polygon id="7" fill="none" stroke="blue" stroke-width="10" points="60,0  60,10  70,10  70,0  60,0 "></polygon><polygon id="8" fill="none" stroke="blue" stroke-width="10" points="70,0  70,10  80,10  80,0  70,0 "></polygon><polygon id="9" fill="none" stroke="blue" stroke-width="10" points="80,0  80,10  90,10  90,0  80,0 "></polygon><polygon id="10" fill="none" stroke="blue" stroke-width="10" points="90,0  90,10  100,10  100,0  90,0 "></polygon><polygon id="11" fill="none" stroke="blue" stroke-width="10" points="100,0  100,10  110,10  110,0  100,0 "></polygon><polygon id="12" fill="none" stroke="blue" stroke-width="10" points="110,0  110,10  120,10  120,0  110,0 "></polygon><polygon id="13" fill="none" stroke="blue" stroke-width="10" points="120,0  120,10  130,10  130,0  120,0 "></polygon><polygon id="14" fill="none" stroke="blue" stroke-width="10" points="130,0  130,10  140,10  140,0  130,0 "></polygon><polygon id="15" fill="none" stroke="blue" stroke-width="10" points="140,0  140,10  150,10  150,0  140,0 "></polygon><polygon id="16" fill="none" stroke="blue" stroke-width="10" points="150,0  150,10  160,10  160,0  150,0 "></polygon><polygon id="17" fill="none" stroke="blue" stroke-width="10" points="160,0  160,10  170,10  170,0  160,0 "></polygon><polygon id="" fill="none" stroke="blue" stroke-width="10" points="160,0 "></polygon><rect id="binRect" x="0" y="10" width="10.05" height="30.05"></rect></svg>`

**Comment by Jack000** [comment]
the underlying issue is that the clipper version of the minkowski sum sometimes generates small, spurious polygons (it's slightly noisy), and to remove these we have to filter out very small nfps that look like singularities. For a more direct solution you could try my other project deepnest.io that avoids this issue with a better minkowski library.

for svgnest it will generally not be able to place a part if the required space is tighter than one pixel. This is a trade off, as having a tighter tolerance would mean that sometimes parts would erroneously overlap. This particular svg is problematic because the parts are only 10px across, while the fit tolerance is calibrated for "real world" sizes where parts are greater than 72px or 1 inch in size. I would recommend scaling your parts up about 5x and ensuring the bin is at least 1px wider than the part at all points.

A simple solution to this would be to scale up all numbers in preprocessing, but this may take some work..

**Comment by finnyexeeson** [comment]
Thank you Jack for the help!
