### ISSUE TITLE
Integration with LaserWeb

### ISSUE THREAD

**Issue by openhardwarecoza** [Jack000/SVGnest#9]
Hi Jack

Do you have a Google Plus profile?  See https://plus.google.com/u/0/+ArthurWolf/posts/eVxYxnQCiHp (Thread on Arthur Wolf's - creater of the Smoothieboard - profiles)

**Comment by openhardwarecoza** [comment]
@bmtm @Jack000 

Just heads up, @jorgerobles is playing with this, may bug you soon for questions

LaserWeb project: github.com/LaserWeb

**Comment by Jack000** [comment]
cool, I'll keep an ear out

**Comment by openhardwarecoza** [comment]
(: I sent you guys invitations to the LaserWeb Organisation too if you'd like to be a part of this greatness

We are up to Version 4 and its now a proper React+ES6+WebGL app (no more threejs, no more plain old js/html like version 1 was) - dropping threejs means we are now using plain old polygon maths, so taking another stab at svgnest may be easier now.   We also build these as Electron binaries now ( see github.com/LaserWeb/LaserWeb4-Binaries ) and support Grbl, Smoothie and TinyG (; 
Todd Fleming from JSCut.org fame joined the project last year and added tonnes of CNC CAM functionality 

G+ Community is just about striking 2000 members.
The Github organisation is 35 devs strong (:

Just busy changing the world!  (; #beapartofit

**Comment by jorgerobles** [comment]
Hi @Jack000, I'm just doing basic research about how it works. I'm totally noob.

My first idea is to compare how SVGNest is doing parsing and with what final data does it works, comparing with our own parser/data

Other idea coming to my mind is that using clipperJs, we could use it to reduce the complex groupings to flat shapes (simple boolean AND?), so we keep the "external shape" reference to do the sorting.  Then put the children elements back on place.  That could be a first shot so "shape on shape" would not be available, but fine for basic packing shapes. Laser people will jawdrop with that.

Not to say, talented people like you @Jack000, @tbfleming, @lautr3k could do on a regular evening :)

**Comment by openhardwarecoza** [comment]
Lol @jorgerobles noob? Go check his contributions graph on
github.com/LaserWeb/LaserWeb4 - top contributors arent noobs!

**Comment by jorgerobles** [comment]
Hahah, thanks @openhardwarecoza, but indeed I'm no algebra man :D

**Comment by Jack000** [comment]
If you're using electron I think a better approach might be to use boost polygon as a native addon. It should be faster/more reliable compared to my implementation, but would need some c++

**Comment by jorgerobles** [comment]
Good idea, indeed @tbfleming told us last week new chrome version supports core c++ programming. I hope Todd could make some time to explain that approach thoroughly

**Comment by Jack000** [comment]
the hardest part of the nesting algo is generating the NFP. There are a few open source implementations that I know of - mine, boost polygon, and CGAL. CGAL is the best, but is GPLv3 and is also harder to work with. boost polygon is BSD I think.

there's a handy tutorial on boost polygon here: http://www.boost.org/doc/libs/1_63_0/libs/polygon/doc/gtl_minkowski_tutorial.htm

the NFP is just the minkowski difference. ie NFP = A (-B)
where -B is the B polygon inverted vertically and horizontally.

**Comment by tbfleming** [comment]
@jorgerobles part of the CAM extends and uses boost.polygon: https://github.com/LaserWeb/web-cam-cpp-src

Right now it builds to asm.js. I'll switch it to wasm when Electron upgrades to Chromium 57. I plan to eventually move the JavaScript parts to C++ to try to solve performance issues.
